### ISSUE TITLE
TOWT predictions cannot predict negative values?

### ISSUE THREAD

**Issue by Cyy-fresh1994** [kW-Labs/nmecr#16]
We used the nmecr to predict annual normalized electricity consumption. 

Our training data has a lot of negative values due to solar PV production. And the model fit by using training data can capture the negatives, see the screenshot below:
![image](https://user-images.githubusercontent.com/66685387/214925255-54316a70-8e63-48cd-89e0-0b91f82242fe.png)

But when we do predictions, the predictions are all positive, it looks like the negative values were cut off, see the screenshot below:
![image](https://user-images.githubusercontent.com/66685387/214925485-0884773a-7276-40b3-9112-df8b4006ea24.png)

Cannot nmecr be used for predicting negative data?

**Comment by dexterluu** [comment]
Hi,

Do you have data and code to replicate the issue? Seems like in the first plot the values can go negative so it doesn't appear to be an issue with the coefficients.

Thanks,
Dexter

**Comment by Cyy-fresh1994** [comment]
Yes, please see attached code and data. Thank you for the help.


Thank you,
Yiyi


From: dexterluu ***@***.***>
Sent: Friday, January 27, 2023 2:08 PM
To: kW-Labs/nmecr ***@***.***>
Cc: Chu, Yiyi ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [kW-Labs/nmecr] TOWT predictions cannot predict negative values? (Issue #16)

This is an EXTERNAL email. Do not click links or open attachments unless you validate the sender and know the content is safe.

ALWAYS hover over the link to preview the actual URL/site and confirm its legitimacy.


Hi,

Do you have data and code to replicate the issue? Seems like in the first plot the values can go negative so it doesn't appear to be an issue with the coefficients.

Thanks,
Dexter

-

**Comment by dexterluu** [comment]
Sorry to have to ask again, but I don't think the attachments went through via email. Can you attach the files on the issue thread on GitHub?

Thanks,
Dexter

**Comment by Cyy-fresh1994** [comment]
[Historical Meter 2.csv](https://github.com/kW-Labs/nmecr/files/10523714/Historical.Meter.2.csv)
[Historical temperature data.csv](https://github.com/kW-Labs/nmecr/files/10523715/Historical.temperature.data.csv)
[TMY2 Temp - San Fran.csv](https://github.com/kW-Labs/nmecr/files/10523716/TMY2.Temp.-.San.Fran.csv)
[nmecr-demo - Copy.txt](https://github.com/kW-Labs/nmecr/files/10523722/nmecr-demo.-.Copy.txt)

The nmecr-demo file should be .rmd, but I cannot upload rmd files. Please change txt to be rmd before you open it.

Thank you,
Yiyi

**Comment by dexterluu** [comment]
Hi Yiyi,

I updated the package and included an argument to allow for negative values in the calculate_model_predictions function. Please reinstall the package to get the change.

Thanks,
Dexter
