### ISSUE TITLE
Data preparation differences in M&V Plan and Predictability Analysis scripts

### ISSUE THREAD

**Issue by samberman1** [kW-Labs/nmecr#29]
**Describe the bug**
The Predictability Analysis and M&V Plan scripts will output slightly different metrics for the same data files, date ranges, and model type.

**To Reproduce**
1. Source M&V Plan scripts
2. Using the same independent and dependent variables as used in (1), source Predictability Analysis. 

**Expected behavior**
Would expect model metrics to be the same between the two outputs. 

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - R version [4.4.1]

**Additional context**
It is due to how the data is prepared for the two models. The M&V Plan uses an additional function "check_data_sufficiency()" (lines 72-87) that cleans up the data and removes a point from the model when it is missing X% of data from a given day. This is not utilized in the Predictability Analysis scripts. In the case where hourly data is poor or missing for a daily model, the Predictability Analysis script will average over the available data for that day, the M&V Plan will remove that day from the model.

**Comment by mhsjacoby** [comment]
This was mistakenly posted in the wrong repository, and is not relevant to NMECR. Marked as closed.
